//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseApp1.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public int AnswerId { get; set; }
        public string Content { get; set; }
        public int QuestionId { get; set; }
        public string UserId { get; set; }
        public System.DateTime CreationDate { get; set; }
    
        public virtual RoomQuestion RoomQuestion { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
