//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseApp1.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int BookId { get; set; }
        public int BookCategory { get; set; }
        public string BookLink { get; set; }
        public string BookTitle { get; set; }
        public string Authors { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
