//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseApp1.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course_lessons
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public int Course_id { get; set; }
        public Nullable<int> Order { get; set; }
    
        public virtual Cours Cours { get; set; }
    }
}
