//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseApp1.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoadmapLink
    {
        public int LinkId { get; set; }
        public int CourseId { get; set; }
        public string Link { get; set; }
        public string Name { get; set; }
    
        public virtual Roadmap_courses Roadmap_courses { get; set; }
    }
}
