//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseApp1.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomQuestion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RoomQuestion()
        {
            this.Answers = new HashSet<Answer>();
        }
    
        public int QuestionId { get; set; }
        public string Content { get; set; }
        public int RoomId { get; set; }
        public string UserId { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<bool> IsAnswered { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Answer> Answers { get; set; }
        public virtual Room Room { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
